version: '3.8'

services:
  db:
    container_name: users_db
    image: 'postgres'
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: